# **IEOR 4404  Simulation (Spring 2020)**

**Homework 1 [Total points: 60]**


**Due 11:59 PM, Feb 11**

Homework 1 consists of application-oriented exercises focusing on Python and Statistics basics

The steps to finish the homework:

*   Step 1: Answer your homework on Google Colab.
*   Step 2: Submit the copy on Google Assignment

Before you submit your assignment, make sure to re-run your code from the beginning. (You can do so by first clicking Runtime/Reset All Runtimes and then clicking Runtime/Run all)



In [2]:
#Your Name:Limeng Lu
#Your UNI:ll3359

In [3]:
#This imports all the packages you need for the homework (you might not use some of them)
#Please run this first
#we will need this for array operation
import numpy as np

#We will need this to calculate factorial on array
import scipy.special as spsp

#Exercise 1 [20 Points]


##Q1. [12 Points]

* Create array **Array1** that contains the following elements: $[1.1, 1,2, 1.3, \dots, 30.0]$


* Generate **Array2** from **Array1** that follows
>* The 1st element in Array2 is the 1st element in Array1. 
>* Starting from the 2nd element in Array 2, we  have
>>* the 2nd element in Array2 is the 2nd element in Array1 minus the 1st element in Array 1
>>*  the 3rd element in Array2 is the 3rd element in Array1 minus the 2nd element in Array1
>>* the 4th element in Array2 is the 4th element in Array1 minus the 3rd element in Array1
>>* ... 


* Based on a conditional statement with 3 branches, print out which condition the average of the **Array2** satisfies (1) smaller than 0.11 (2) between 0.11 and 0.13 (3) higher than 1.3. 

* Compute the sum of square roots of all the even elements in Array1 (2nd element, 4th element, 6th element,...).



For this question, `np.repeat`, `np.linspace` functions, and loops are not allowed.  


In [4]:
#Create Array1
Array1=np.arange(1.1,30.1,0.1)
print(Array1)

[ 1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4
  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8
  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2
  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6
  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.
  8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4
  9.5  9.6  9.7  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7 10.8
 10.9 11.  11.1 11.2 11.3 11.4 11.5 11.6 11.7 11.8 11.9 12.  12.1 12.2
 12.3 12.4 12.5 12.6 12.7 12.8 12.9 13.  13.1 13.2 13.3 13.4 13.5 13.6
 13.7 13.8 13.9 14.  14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15.
 15.1 15.2 15.3 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1 16.2 16.3 16.4
 16.5 16.6 16.7 16.8 16.9 17.  17.1 17.2 17.3 17.4 17.5 17.6 17.7 17.8
 17.9 18.  18.1 18.2 18.3 18.4 18.5 18.6 18.7 18.8 18.9 19.  19.1 19.2
 19.3 19.4 19.5 19.6 19.7 19.8 19.9 20.  20.1 20.2 20.3 20.4 20.5 20.6
 20.7 20

In [5]:
#Create Array2
Array2=np.append(Array1[0],np.diff(Array1))  
print(Array2)

[1.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1
 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.

In [6]:
#Construct your conditional statement here
AV=np.mean(Array2)
if AV<0.11:
    print("condition 1 satisfied")
elif AV<=0.13:
    print("condition 2 satisfied")
else:
    print("condition 3 satisfied")

condition 1 satisfied


In [7]:
#Compute the sum of the square roots of all the even elements in Array1 
np.sum(Array1[1::2]**0.5)

546.6210292094935

##Q2.  [8 Points]

* Convert Array1 to a list List1.
* Run a `for` loop 50 times. Each time, append an element equals the last element of List 1 plus 0.2 to the back of List1. 
* Print out the last 10 elements of List1.

In [8]:
#Convert Array1 to a list List1
List1=Array1.tolist()
print(List1)

[1.1, 1.2000000000000002, 1.3000000000000003, 1.4000000000000004, 1.5000000000000004, 1.6000000000000005, 1.7000000000000006, 1.8000000000000007, 1.9000000000000008, 2.000000000000001, 2.100000000000001, 2.200000000000001, 2.300000000000001, 2.4000000000000012, 2.5000000000000013, 2.6000000000000014, 2.7000000000000015, 2.8000000000000016, 2.9000000000000017, 3.0000000000000018, 3.100000000000002, 3.200000000000002, 3.300000000000002, 3.400000000000002, 3.500000000000002, 3.6000000000000023, 3.7000000000000024, 3.8000000000000025, 3.9000000000000026, 4.000000000000003, 4.100000000000003, 4.200000000000003, 4.3000000000000025, 4.400000000000003, 4.5000000000000036, 4.600000000000003, 4.700000000000003, 4.800000000000003, 4.900000000000004, 5.0000000000000036, 5.100000000000003, 5.200000000000003, 5.300000000000004, 5.400000000000004, 5.5000000000000036, 5.600000000000003, 5.700000000000005, 5.800000000000004, 5.900000000000004, 6.0000000000000036, 6.100000000000005, 6.200000000000005, 6

In [9]:
#Construct your `for` loop here
for i in range(50):
    List1.append(List1[-1]+0.2)
print(List1)

[1.1, 1.2000000000000002, 1.3000000000000003, 1.4000000000000004, 1.5000000000000004, 1.6000000000000005, 1.7000000000000006, 1.8000000000000007, 1.9000000000000008, 2.000000000000001, 2.100000000000001, 2.200000000000001, 2.300000000000001, 2.4000000000000012, 2.5000000000000013, 2.6000000000000014, 2.7000000000000015, 2.8000000000000016, 2.9000000000000017, 3.0000000000000018, 3.100000000000002, 3.200000000000002, 3.300000000000002, 3.400000000000002, 3.500000000000002, 3.6000000000000023, 3.7000000000000024, 3.8000000000000025, 3.9000000000000026, 4.000000000000003, 4.100000000000003, 4.200000000000003, 4.3000000000000025, 4.400000000000003, 4.5000000000000036, 4.600000000000003, 4.700000000000003, 4.800000000000003, 4.900000000000004, 5.0000000000000036, 5.100000000000003, 5.200000000000003, 5.300000000000004, 5.400000000000004, 5.5000000000000036, 5.600000000000003, 5.700000000000005, 5.800000000000004, 5.900000000000004, 6.0000000000000036, 6.100000000000005, 6.200000000000005, 6

In [10]:
#Print out the last 10 elements of List1
print(List1[-10:])

[38.20000000000011, 38.40000000000011, 38.600000000000115, 38.80000000000012, 39.00000000000012, 39.200000000000124, 39.40000000000013, 39.60000000000013, 39.80000000000013, 40.000000000000135]


#Exercise 2 [30 Points]



##Setting 

Logarithmic distribution is a popular distribution in insurance study to model insurance claim frequency.

The PMF of logarithmic distribution is as follows:

$$PMF(x)=\frac{-p^x}{xln(1-p)}$$, where $x=1, 2, 3, \dots, \infty$. 

The mean of the distribution is equal to $\frac{-1}{ln(1-p)}\frac{p}{1-p}$
The variance of the distribution is equal to $-\frac{p^2+p ln(1-p)}{(1-p)^2(ln(1-p))^2}$

##Q1 [6 Points]

* Fill in the function to use the direct method to compute the PMF for $x=1, \dots, k$. This computation needs to be based on array operations. No loops are allowed.

* Assume that p=0.8, run the function constructed to return the PMF for $x=1, \dots, 20$.

In [11]:
def LogDist_direct (p,k):
  #Fill in the operations here
    x=np.arange(1,k+1)
    PMF=-p**x/x/np.log(1-p)
    return PMF

In [12]:
##Call the function to return PMF corresponding to x=1, ..., 20
#print out the PMF array result
LogDist_direct (p=0.8,k=20)

array([4.97067948e-01, 1.98827179e-01, 1.06041162e-01, 6.36246973e-02,
       4.07198063e-02, 2.71465375e-02, 1.86147686e-02, 1.30303380e-02,
       9.26601814e-03, 6.67153306e-03, 4.85202404e-03, 3.55815097e-03,
       2.62755764e-03, 1.95189996e-03, 1.45741864e-03, 1.09306398e-03,
       8.23012876e-04, 6.21831951e-04, 4.71283163e-04, 3.58175204e-04])

##Q2 [8 Points]

* Fill in the function to use the iterative method to compute the PMF for $x=1, \dots k$

* Assume that p=0.8, run the function constructed to return the PMF for $x=1, \dots, 20$.


In [13]:
def LogDist_iterative (p, k):
  #Fill in the operations here
    PMF_temp=-p/np.log(1-p)
    PMF=np.empty(k)
    PMF[0]=PMF_temp
    for i in range(2,k+1):
        PMF_temp=PMF_temp*p*(i-1)/i
        PMF[i-1]=PMF_temp
    return PMF

In [14]:
##Call the function to return PMF corresponding to x=1, ..., 20 and p=0,8
#print out the PMF array result
LogDist_iterative (p=0.8, k=20)

array([4.97067948e-01, 1.98827179e-01, 1.06041162e-01, 6.36246973e-02,
       4.07198063e-02, 2.71465375e-02, 1.86147686e-02, 1.30303380e-02,
       9.26601814e-03, 6.67153306e-03, 4.85202404e-03, 3.55815097e-03,
       2.62755764e-03, 1.95189996e-03, 1.45741864e-03, 1.09306398e-03,
       8.23012876e-04, 6.21831951e-04, 4.71283163e-04, 3.58175204e-04])

## Q3 [6 Points]

* Construct a function to return the mean and variance of the distribution

* Print out the mean and variance of this distribution assuming $p=0.8$

In [18]:
def LogDist_mv (p):
  #Fill in the operations here
  mean=-1/np.log(1-p)*p/(1-p)
  variance=-(p**2+p*np.log(1-p))/(1-p)**2/(np.log(1-p))**2
  return mean, variance

In [19]:
##Call the function to return PMF corresponding to x=1, ..., 20 and p=0,8
#print out the PMF array result
LogDist_mv (0.8)

(2.4853397382384474, 6.249785076725087)

##Q4 [10 Points]

The expected value of a discrete distribution follows:

$E(x)=\sum_i x_i p_i$

For the distribution we work with, we need to sum up infinite terms. If we only sum up $x_i p_i$ from $i=1$ up to $i=k$, where $k$ is a large value, we can get a good approximation although not exact.

Construct an array that gives how much error we have for the expected value when we choose k=1, 2, ..., 30. 

In [20]:
#construct the array here 
PMF=LogDist_direct (p=0.8,k=30)
x=np.arange(1,31)
Estimation=np.cumsum(PMF*x)
Error_array=Estimation-LogDist_mv(p=0.8)[0]
print(np.abs(Error_array))

[1.98827179 1.59061743 1.27249395 1.01799516 0.81439613 0.6515169
 0.52121352 0.41697082 0.33357665 0.26686132 0.21348906 0.17079125
 0.136633   0.1093064  0.08744512 0.06995609 0.05596488 0.0447719
 0.03581752 0.02865402 0.02292321 0.01833857 0.01467086 0.01173669
 0.00938935 0.00751148 0.00600918 0.00480735 0.00384588 0.0030767 ]


#Exercise 3 [10 Points]



##Setting 


A continuous distribution B has the following probability density function (PDF):

$f(x)=\frac{1}{150}t(t - 5) +\frac{2}{45}, \text{where }  0\leq x \leq 10$


##Q1 [6 Points]





Construct a function to do the following:
* Generate 1000 evenly spaced points between 0 and 20. 
* Compute the pdf corresponding to each point based on Boolean mask


In [21]:
def continuous_pdf():
    #Fill in the operations here
    x=np.linspace(0,20,1000)
    pdf=1/150*x*(x-5)+2/45
    pdf[x>10]=0
    return pdf

#print the pdf array
continuous_pdf()

array([0.04444444, 0.04377978, 0.04312046, 0.04246649, 0.04181786,
       0.04117457, 0.04053663, 0.03990403, 0.03927678, 0.03865487,
       0.03803831, 0.03742708, 0.03682121, 0.03622067, 0.03562548,
       0.03503564, 0.03445113, 0.03387198, 0.03329816, 0.03272969,
       0.03216657, 0.03160879, 0.03105635, 0.03050925, 0.02996751,
       0.0294311 , 0.02890004, 0.02837432, 0.02785395, 0.02733892,
       0.02682923, 0.02632489, 0.02582589, 0.02533224, 0.02484393,
       0.02436096, 0.02388334, 0.02341107, 0.02294413, 0.02248254,
       0.0220263 , 0.0215754 , 0.02112984, 0.02068963, 0.02025476,
       0.01982523, 0.01940105, 0.01898221, 0.01856872, 0.01816057,
       0.01775776, 0.0173603 , 0.01696819, 0.01658141, 0.01619998,
       0.0158239 , 0.01545316, 0.01508776, 0.01472771, 0.014373  ,
       0.01402363, 0.01367961, 0.01334094, 0.0130076 , 0.01267961,
       0.01235697, 0.01203967, 0.01172771, 0.0114211 , 0.01111983,
       0.0108239 , 0.01053332, 0.01024809, 0.00996819, 0.00969

## Q2 [4 Points]

* Print out the average pdf for the points we sampled between 1.00001 and 1.02001 based on Boolean mask

In [22]:
x=np.linspace(0,20,1000)
pdf_avg=continuous_pdf()[(x>=1.00001) * (x<=1.02001) ]
print(pdf_avg)

[0.01775776]
